language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
matrix:
  fast_finish: true
install:
  - python bootstrap.py --buildout-version=2.5.3 --setuptools-version=20.1.1
  - bin/buildout annotate
  - bin/buildout
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage run bin/test
  - pip install -q coveralls
  - coveralls
after_failure:
  - bin/csslint --version
  - bin/jshint --version
  - bin/jscs --version
